# -*- coding: utf-8 -*-
"""EMTECH2_FINALEXAM_SORIANO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BuzoVBYQ64iaCJhsSYKQu8T4al-9XH_T
"""

# Commands needed for deployment

import streamlit as st
import tensorflow as tf

@st.cache(allow_output_mutation=True)
def load_model():
  model=tf.keras.models.load_model('bestbest_model.h5')
  return model
model=load_model()
st.write("""
# Weather Prediction Application 
# Predict the weather like a weather forecaster"""
)
file=st.file_uploader("Upload any weather-related image...",type=["jpg","png"])

import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(224,224)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please choose any weather-related image...")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names=['Cloudy', 'Rain', 'Shine', 'Sunrise']
    string="THE WEATHER IS : "+class_names[np.argmax(prediction)]
    st.success(string)